env:
  global:
    - secure: k3n5bwXWBcROmmU+i2Th0kzs8rkufkPPiNJLSPtF/M221hv462VKVR8aF2MWb2cvB1zeWajBGnRfgCaC7C5ZHlaLQExEQuO+QKkr2aoSwZW1UH76s5HSM1GocZoTx8qfjHV1U72p4mLs3qQ6m9ns5bp4dA/WzYKWjV/4dF8VoII=

language: rust
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc 

after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
