[package]
name = "self_encryption"
version = "0.2.5"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://maidsafe.net/self_encryption/latest"
repository = "https://github.com/maidsafe/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[features]
unstable = []

[dependencies]
asynchronous = "~0.4.5"
rustc-serialize = "~0.3.16"
sodiumoxide = "~0.0.9"
flate2 = "~0.2.11"
memmap = "~0.2.3"

[dev-dependencies]
tempdir = "~0.3.4"
docopt = "~0.6.78"
rand = "~0.3.12"
cbor = "~0.3.16"

[[example]]
name = "basic_encryptor"
path = "examples/basic_encryptor.rs"
test = true
bench = false
