[package]
name = "self_encryption"
version = "0.2.4"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://maidsafe.net/self_encryption/latest"
repository = "https://github.com/maidsafe/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[features]
unstable = []

[dependencies]
asynchronous = "0.4.5"
cbor = "0.3.16"
docopt = "0.6.75"
rustc-serialize = "0.3.16"
sodiumoxide = "0.0.9"
tempdir = "0.3.4"
flate2 = "0.2.11"
memory_map = "0.0.2"

[dev-dependencies]
rand = "0.3.12"

[[example]]
name = "basic_encryptor"
path = "examples/basic_encryptor.rs"
test = true
bench = false
