[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://docs.maidsafe.net/self_encryption/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.7.0"

[dependencies]
brotli2 = "~0.2.1"
clippy = {version = "~0.0.94", optional = true}
memmap = "~0.4.0"
rand = "~0.3.14"
rust_sodium = "~0.1.2"
rustc-serialize = "~0.3.19"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.86"
itertools = "~0.5.2"
#maidsafe_utilities = "~0.9.0"
maidsafe_utilities = { path = "../../maidsafe-utilities/maidsafe_utilities" }

[[example]]
name = "basic_encryptor"
