[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://docs.maidsafe.net/self_encryption/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.7.0"

[dependencies]
brotli2 = "~0.2.1"
futures = "~0.1.11"
memmap = "~0.4.0"
rand = "~0.3.14"
serde = "~0.9.12"
serde_derive = "~0.9.12"
rust_sodium = "~0.2.0"
unwrap = "~1.1.0"

[dev-dependencies]
rustc-serialize = "~0.3.23"
docopt = "~0.6.81"
itertools = "~0.4.16"
maidsafe_utilities = "~0.11.0"

[[example]]
name = "basic_encryptor"
