[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://maidsafe.net/self_encryption/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.3.1"

[dependencies]
brotli2 = "~0.1.0"
clippy = {version = "~0.0.64", optional = true}
maidsafe_utilities = "~0.5.4"
memmap = "~0.3.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"

[dev-dependencies]
docopt = "~0.6.80"

[[example]]
name = "basic_encryptor"
