[package]

name = "self_encryption"
version = "0.0.2"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/self_encryption/self_encryption"
repository = "https://github.com/dirvine/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rust-crypto = "*"
semver = "0.1.14"
rand = "0.1.3"

