[package]

name = "self_encryption"
version = "0.0.3"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://rust-ci.org/dirvine/self_encryption"
repository = "https://github.com/dirvine/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide"

[dependencies]
rand = "0.1.3"
rust-crypto ="*"

